// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.

function getEvenFibonacciSum(maxFibValue) {
  let index1 = 0
  let index2 = 1
  let totalSum = 0
  do {
    indexSum = index1 + index2
    if (indexSum % 2 == 0)
      totalSum += indexSum
    index1 = index2
    index2 = indexSum
  } while((index1 + index2) < maxFibValue)
  return console.log(totalSum)
}

getEvenFibonacciSum(maxFibValue=4000000)